### ISSUE TITLE
'exceptionHandling()' is deprecated since version 6.1 and marked for removal in 7.0

### ISSUE THREAD

**Issue by benstrydom** [wimdeblauwe/error-handling-spring-boot-starter#100]
Documentation 4.4.0 Section 3.9.1 and 3.9.2
Replace `http.exceptionHandling().authenticationEntryPoint(unauthorizedEntryPoint);` with
`http.exceptionHandling(customizer -> customizer.authenticationEntryPoint(unauthorizedEntryPoint));`
and `http.exceptionHandling().accessDeniedHandler(accessDeniedHandler);`
`with http.exceptionHandling(customizer -> customizer.accessDeniedHandler(accessDeniedHandler));`

**Comment by wimdeblauwe** [comment]
Thanks for letting me know!
