### ISSUE TITLE
Usage with spring-starter-web-flux

### ISSUE THREAD

**Issue by ghost** [wimdeblauwe/error-handling-spring-boot-starter#2]
Hey there,
we've trouble running `error-handling-spring-boot-starter` with `spring-starter-web-flux` in combination with `spring-boot-starter-security`.
Webflux uses `ControllerMethodResolver` instead of `ExceptionHandlerExceptionResolver` from spring-starter-web and fails to register the ControllerAdvice beans.
unfortunately we can not just add spring-starter-web, because its `WebSecurityConfiguration` collides with Webflux's `WebFluxSecurityConfiguration`.

Have you any advice, how to integrate `error-handling-spring-boot-starter` with `spring-starter-web-flux`?
Thanks in advice and keep up the great work

**Comment by wimdeblauwe** [comment]
You are right, the code only works for servlet environments, see:
https://github.com/wimdeblauwe/error-handling-spring-boot-starter/blob/0.3.0/src/main/java/io/github/wimdeblauwe/errorhandlingspringbootstarter/ErrorHandlingConfiguration.java#L18

As I am currently not using Webflux, I don't have a need for this. 

I see the following options:
1. You can see if https://github.com/alimate/errors-spring-boot-starter solves your needs as it does have support for Webflux
2. Feel free to submit a PR to support Webflux here.
3. Wait until I too have the need for Webflux, but I don't think this will happen in the first few months.

**Comment by fabiomarini** [comment]
Hi, I just added PR #44 to add support for Project Reactor and WebFlux applications

**Comment by wimdeblauwe** [comment]
The version 3.0.0-rc.1 has been released with support for spring-starter-web-flux: https://github.com/wimdeblauwe/error-handling-spring-boot-starter/releases/tag/3.0.0-rc.1

Please give it a try and let me know how it goes!

**Comment by wimdeblauwe** [comment]
Version 3.0.0 is now released.
