### ISSUE TITLE
Handling exceptions from filters

### ISSUE THREAD

**Issue by axelmederer** [wimdeblauwe/error-handling-spring-boot-starter#28]
Hi,

I'm trying to catch exceptions thrown from Spring Filters with `ErrorHandlingControllerAdvice`. I'm aware that `@ControllerAdvice` annotated classes aren't meant to catch those exceptions, which is why I'm implementing something similar to what's described here: https://stackoverflow.com/a/55864206/14789719

The problem I'm having is that `HandlerExceptionResolver.resolveException()` doesn't call `ErrorHandlingControllerAdvice` to handle the exception. I think this is because Spring sees that `ErrorHandlingControllerAdvice` is annotated with `@ControllerAdivce(annotations = RestController.class)` which tells Spring that it should only call it to handle exceptions thrown from `@RestController` annotated classes.

I understand that, in normal circumstances, that is the obvious and desired functionality, but it would be really convenient for me to call `ErrorHandlingControllerAdvice` from filters. Do you think there is some way to accomodate my use case?

Thank you very much for your time and for the library.

**Comment by wimdeblauwe** [comment]
Have you tried to autowire `io.github.wimdeblauwe.errorhandlingspringbootstarter.ErrorHandlingControllerAdvice` directly? As `@ControllerAdvice` is annoted with `@Component`, it should be available in the context for autowiring.

**Comment by axelmederer** [comment]
I thought about it, but I don't how to get the `WebRequest` object that is needed to call `handleException`.

**Comment by axelmederer** [comment]
There's also another thing, by calling the `io.github.wimdeblauwe.errorhandlingspringbootstarter.ErrorHandlingControllerAdvice` directly, I have to then write it the `ResponseEntity` myself in the body of the response, which means that I have to check if the client wants XML or JSON and other things. By calling `HandlerExceptionResolver.resolveException()` Spring would be the one to take care of it.

Again, it's just convenience, if you think that it is too problematic, I understand.

**Comment by wimdeblauwe** [comment]
I don't want to remove the `annotations =RestController.class` part since that is needed if you have a project that uses both `@Controller` and `@RestController`. Unsure what the best way forward is for your use case. You could fork the project and adjust it on your own fork and release that to yourself locally, if you are willing to keep your fork then up-to-date with future changes. (If that is all that is needed to make it work, I have no clue as I have no example project to test on).

**Comment by axelmederer** [comment]
I understand, don't worry. For now I've just resorted to calling `io.github.wimdeblauwe.errorhandlingspringbootstarter.ErrorHandlingControllerAdvice` like you suggested previously and it works well. 

I may try your suggestion of forking the project to confirm if just removing the annotation would make it work for my case. If you are interested in what I find, I can comment it on this issue. I don't make any promises though, because that part is good enough for now and there are some other things I have to focus on.

Thanks once again for your time. I like this library a lot and I appreciate that you've listened to a request of mine for the second time now. As to whether to leave this issue open or closed, I'll leave that up to you.

Have a nice day.

**Comment by wimdeblauwe** [comment]
I'll close the issue for now as I don't see anything I can do further to help your use case while keeping the goal of the project in mind.  But do feel free to comment on the issue with your findings, I am interested to hear more.
