### ISSUE TITLE
Supress Resolved warning in the logs

### ISSUE THREAD

**Issue by DanielDimov** [wimdeblauwe/error-handling-spring-boot-starter#32]
I put error.handling.exception-logging=NO_LOGGING in my properties file, but Resolved warning still goes in my logs. Is there any way to prevent this with some configuration?

**Comment by maksimkurb** [comment]
@DanielDimov It's controlled by `spring.mvc.log-resolved-exception` property. By default, it's `false`, but if you add spring-boot-devtools to your project, it will become `true`.
