### ISSUE TITLE
404

### ISSUE THREAD

**Issue by michaldo** [wimdeblauwe/error-handling-spring-boot-starter#34]
The library does not handle 404 exception, isn't it?

Is there any hint how to handle 404?

**Comment by wimdeblauwe** [comment]
Can you elaborate on what you tried exactly and what is not working?

**Comment by michaldo** [comment]
I created blank project from Spring Initializer with web starter and Java 11
I added single rest controller
```
@GetMapping String hello() {
    throw new UnsupportedOperationException("foo");}
```
Without error starter, I got:

> curl localhost:8080
> {"timestamp":"2022-01-05T18:10:58.405+00:00","status":500,"error":"Internal Server Error","path":"/"}
> curl localhost:8080/no
> {"timestamp":"2022-01-05T18:11:07.621+00:00","status":404,"error":"Not Found","path":"/no"}

The I added 
```
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'io.github.wimdeblauwe:error-handling-spring-boot-starter:1.7.0'
```
(error starter does not work standalone, I had to add validation starter)

After adding starter, I retried command and I got:

> curl localhost:8080
> {"code":"UNSUPPORTED_OPERATION","message":"foo"}
> curl localhost:8080/no
> {"timestamp":"2022-01-05T18:15:43.671+00:00","status":404,"error":"Not Found","path":"/no"}

Therefore I think error starter does not handle 404 error

**Comment by wimdeblauwe** [comment]
Sorry I don't have much time now, but you are right. Maybe try the solution presented at https://stackoverflow.com/a/54002078/40064 to see if that helps?

**Comment by michaldo** [comment]
Unfortunately it doesn't solve the case.

I think that if I want uniform exception response handling, with the same structure for exceptions from application, filters, Spring MVC like 400, 405, 404, then I should choose solution based on org.springframework.boot.web.servlet.error.ErrorAttributes, not based on controller advice like your library

**Comment by wimdeblauwe** [comment]
I just tried it and I got it working like this:

1) Add the following properties to `application.properties`:

```
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
```

2) Add the following class in your project:

```
import io.github.wimdeblauwe.errorhandlingspringbootstarter.ApiErrorResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.NoHandlerFoundException;

@ControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(NoHandlerFoundException.class)
    public ResponseEntity<?> handleNotFoundError(NoHandlerFoundException exception) {
        return ResponseEntity.status(HttpStatus.NOT_FOUND)
                             .body(new ApiErrorResponse(HttpStatus.NOT_FOUND, "NOT_FOUND", exception.getMessage()));
    }
}
```

This results in the following response:

```
{
  "code": "NOT_FOUND",
  "message": "No handler found for GET /no"
}
```

**Comment by michaldo** [comment]
Works, thanks
