### ISSUE TITLE
Status Code not included in JSON

### ISSUE THREAD

**Issue by Dutzen** [wimdeblauwe/error-handling-spring-boot-starter#40]
The status code is not included in the json.

I tried version 1.6.0, 1.7.0, 2.0.0. but in neither the status code '409' is included in the json response

i enabled it via property

> error.handling.http-status-in-json-response=true

The Error class:
``` 
@ResponseStatus(HttpStatus.CONFLICT)
public class DuplicateException extends RuntimeException {

    @ResponseErrorProperty(includeIfNull = true)
    private final String objectName;
    @ResponseErrorProperty(includeIfNull = true)
    private final Map<String, String> identifierMap;
    private final String x = "asd";


    public DuplicateException(String objectName, Map<String, String> identifierMap) {
        super(String.format("%s already exists with parameters: %s", objectName, identifierMap));
        this.objectName = objectName;
        this.identifierMap = identifierMap;

    }
}
```

The Json Response:
```{
  "code": "DUPLICATE",
  "message": "Channel already exists with parameters: {name=asd}",
  "objectName": "Channel",
  "identifierMap": {
    "name": "asd"
  }
}
```

**Comment by wimdeblauwe** [comment]
Sorry, I lost track of this. Do you have a small reproducer so I can have a look?

**Comment by Dutzen** [comment]
I created a new project containing only the required dependencies. Unfortunatelly (or not) the status code is included in the stripped project.

The problem still persists in my main project, so i try to figure out, what the differences are.
If i find something out, i will report it 

Basically the code is simple: i created a rest controller, and the DuplicateException class. Within the controller i throw the exception.

**Comment by wimdeblauwe** [comment]
That is weird. In that stripped project, are you using the exact same Exception class with those fields? Do let me know if you find something and I'll have a look to see if it can be fixed.

**Comment by sverhagen** [comment]
It is not possible for me to conclude that @Dutzen was in fact having the same situation, but I noticed one of our projects also omitting the `status` field, and I would like to let you know what caused this, in case anyone else stumbles upon this issue. This particular project had a custom `ObjectMapper` defined and injected into the application context as an `@Primary` `@Bean`. This `ObjectMapper` was poorly constructed, to the extent that the `ApiErrorResponseSerializer` from `error-handling-spring-boot-starter` wasn't added to its configuration. As a result, it used Jackson's default serialization, which encounters that `ApiErrorResponse` does not have a `status` field; it has a `httpStatus` field (but that one is annotated with `@JsonIgnore`). I frankly do not understand why `ApiErrorResponse` needs a non-default serializer, it looks like it could be serialized by Jackson just fine, but in any case, refactoring my project to not create a custom `ObjectMapper` bean anymore solved the problem for me.

**Comment by wimdeblauwe** [comment]
Thank you for your comment. This might certainly help others debug similar issues.

FYI: The custom serializer is needed because of some customizations that can be done to the output like changing the names of the JSON fields via the `error.handling.json-field-names.*` properties.
