### ISSUE TITLE
Project Reactor support

### ISSUE THREAD

**Issue by inputinput77777** [wimdeblauwe/error-handling-spring-boot-starter#41]
Is there any support for Spring Webflux (i.e. Project Reactor with Spring)?

I think it'll be super useful for a lot of people.

**Comment by wimdeblauwe** [comment]
There is not currently, see https://github.com/wimdeblauwe/error-handling-spring-boot-starter/issues/2

**Comment by fabiomarini** [comment]
Hi, I just added PR #44 to add support for Project Reactor and WebFlux applications

**Comment by wimdeblauwe** [comment]
The version 3.0.0-rc.1 has been released with support for project reactor: https://github.com/wimdeblauwe/error-handling-spring-boot-starter/releases/tag/3.0.0-rc.1

Please give it a try and let me know how it goes!

**Comment by wimdeblauwe** [comment]
Version 3.0.0 is now released.
