### ISSUE TITLE
Suggestions on List field validation?

### ISSUE THREAD

**Issue by sdoxsee** [wimdeblauwe/error-handling-spring-boot-starter#49]
Example:

```java
@Service
class SomeService { 
   void doSomething(List<@Valid SomeItem> someItems) {}
}
```

Currently, `ApiFieldError` doesn't have a place to indicate which item within a list has the validation issue. Would it be worth adding an optional property of `ApiFieldError` like `index` to indicate the index of the problematic object in the List? I realize `index` may not help with `Map<String, @Valid SomeItem>`, for instance, or other structures. Currently we've had to reimplement `ConstraintViolationApiExceptionHandler`.

Thanks!

**Comment by wimdeblauwe** [comment]
For a map like this:

```
        void doSomethingWithMap(Map<String, @Valid TestRequestBody> map) {

        }
```

This would be resulting JSON:

```
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed. Error count: 3",
  "fieldErrors": [
    {
      "code": "REQUIRED_NOT_NULL",
      "message": "must not be null",
      "property": "value",
      "rejectedValue": null,
      "propertyPath": "doSomethingWithMap.map[key2].value"
    },
    {
      "code": "INVALID_SIZE",
      "message": "size must be between 1 and 255",
      "property": "value2",
      "rejectedValue": "",
      "propertyPath": "doSomethingWithMap.map[key2].value2"
    }
  ],
  "globalErrors": [
    {
      "code": "ValuesEqual",
      "message": "Values not equal",
      "propertyPath": "doSomethingWithMap.map[key2]"
    }
  ]
}
```

**Comment by wimdeblauwe** [comment]
For a Set, it would be this:

```
        void doSomethingWithSet(Set<@Valid TestRequestBody> set) {

        }
```

JSON result:

```
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed. Error count: 3",
  "fieldErrors": [
    {
      "code": "INVALID_SIZE",
      "message": "size must be between 1 and 255",
      "property": "value2",
      "rejectedValue": "",
      "propertyPath": "doSomethingWithSet.set[].value2"
    },
    {
      "code": "REQUIRED_NOT_NULL",
      "message": "must not be null",
      "property": "value",
      "rejectedValue": null,
      "propertyPath": "doSomethingWithSet.set[].value"
    }
  ],
  "globalErrors": [
    {
      "code": "ValuesEqual",
      "message": "Values not equal",
      "propertyPath": "doSomethingWithSet.set[]"
    }
  ]
}
```

**Comment by sdoxsee** [comment]
Thanks @wimdeblauwe. 

At first glance, that looks sufficient and also should handle even further nesting of various types. I only question the `doSomethingWithX.y` prefix as I don't see why people would need the method and argument name (or if that should even be exposed?). I would think it's more the content of the argument being validated that one would care about?

So for 
* `List` -> `[0].value`
* `Map` -> `[key].value`
* `Set` -> `[].value`

I'll circle back tomorrow and will think about it a bit more but please share any more thoughts you might have. Cheers

**Comment by wimdeblauwe** [comment]
I agree with you. It is the reason I did _not_ add `propertyPath` in the first place as I also feel it exposes too much internal information.

I'll add some more tests with further nesting to see how that behaves if I have time. Maybe we can build something intelligent that strips out the first part of the `propertyPath` as that seems irrelevant indeed.

**Comment by sdoxsee** [comment]
If you're not already too deep into it, would you mind if I expanded the tests to try this out myself in a PR? Would like to save you some time! The design intention would be as you suggested but without the method and argument name (i.e. basically the @Valid object in its context)

**Comment by wimdeblauwe** [comment]
Sure, go ahead!
