### ISSUE TITLE
Support logging level based on response status

### ISSUE THREAD

**Issue by namhokim** [wimdeblauwe/error-handling-spring-boot-starter#57]
Basically when exception is throw without other exception handler, then wimdeblauwe error handler handle with put the log of error level. (Line 31, 34)

https://github.com/wimdeblauwe/error-handling-spring-boot-starter/blob/bac6c3fba0b735c044ca78f1999c6a5d2d9ee2e8/src/main/java/io/github/wimdeblauwe/errorhandlingspringbootstarter/LoggingService.java#L28-L37

How can I change the to another logging level?

**Comment by wimdeblauwe** [comment]
That is not possible. The logging is always at error level. Why would you want to use another logging level?

**Comment by namhokim** [comment]
There are normal error responses: usually user input error is normal situation. 
So some error should be logging with warning level.
Because our company has policy that error level log seems to be the problem and notice by alarm system.
So I want to change log level lower.

**Comment by wimdeblauwe** [comment]
Ah, I understand why now better. So you would like to be able to define a mapping between error response codes and log levels somehow?


Something like this:
```
error.handling.log-levels.400=DEBUG
error.handling.log-levels.5xx=ERROR
```

**Comment by wimdeblauwe** [comment]
Version 4.1.0 (for Spring Boot 3.x) release with support for this. Also backported as 3.4.0 for Spring Boot 2.7.x.

**Comment by namhokim** [comment]
@wimdeblauwe Thank you very much!
I will try version 3.4.0.
