### ISSUE TITLE
error.handling.log-levels property is not being overridden

### ISSUE THREAD

**Issue by tddiaz** [wimdeblauwe/error-handling-spring-boot-starter#64]
I would like to override the default values of the log-levels to
```
error:
  handling:
    log-levels:
      4xx: WARN
      500: ERROR
```
but still the exception is being logged as ERROR
```
2023-02-02T22:55:43.450+04:00 ERROR 9014 --- [           main] i.g.w.e.LoggingService                   : checkEmail.email: Invalid email address
```
I tried debugging the LoggingService and the logLevels props is empty
<img width="922" alt="Screenshot 2023-02-02 at 10 59 19 PM" src="https://user-images.githubusercontent.com/7876492/216425323-bbd8f8e9-d0ad-445a-84fa-ff619f4292b7.png">

I have also tried adding `@EnableConfigurationProperties(ErrorHandlingProperties::class)` but still not working

Spring Boot v3.0.1
Java 19
Error Handling Spring Boot Starter v4.1.0

**Comment by wimdeblauwe** [comment]
Can you try using a `properties` file instead of `yaml` to see if that is the issue?

**Comment by tddiaz** [comment]
Fixed the problem. It turned out my properties file is not being picked up propertly.
