### ISSUE TITLE
Does `@ErrorResponseProperty` work with inheritance?

### ISSUE THREAD

**Issue by almibarss** [wimdeblauwe/error-handling-spring-boot-starter#67]
I would like to define a common base exception that provides an error code for every error response in my application. This is what I've come up with:

```java
public class ApplicationError extends RuntimeException {

  @ResponseErrorProperty("code")
  protected final String useCaseCode;

  public ApplicationError(String useCaseCode, String message) {
    super(message);
    this.useCaseCode = useCaseCode;
  }
}
```

```java
public class ResourceNotFoundException extends ApplicationError {

  public ResourceNotFoundException(String useCaseCode, Class<?> resource, String resourceId) {
    super(useCaseCode, resource.getSimpleName() + " with id " + resourceId + " not found");
  }
}
```

Unfortunately the `code` field is not being serialized. Is that a known limitation of custom error fields?

**Comment by wimdeblauwe** [comment]
This is indeed an issue, thanks for reporting. It will be fixed in the next version. You can add a getter method and put it on the method instead of the field as a workaround.

**Comment by wimdeblauwe** [comment]
https://github.com/wimdeblauwe/error-handling-spring-boot-starter/releases/tag/4.1.2

**Comment by almibarss** [comment]
It works like a charm now. Thank you very much @wimdeblauwe ❤️
