### ISSUE TITLE
Add ConditionalOnMissingBean to all beans in AbstractErrorHandlingConfiguration

### ISSUE THREAD

**Issue by ooraini** [wimdeblauwe/error-handling-spring-boot-starter#73]
I'm trying to customize the ErrorMessageMapper, but I see that the bean is added unconditionally to the application context. If it doesn't cause any issues, can we add @ConditionalOnMissingBean to all the beans?

**Comment by wimdeblauwe** [comment]
Might be a good idea indeed. Why do you need to customize it?

**Comment by ooraini** [comment]
Hi, I want to hook in MessageSource for translation, seems like the logical place for it.

**Comment by wimdeblauwe** [comment]
Implemented in #74

**Comment by wimdeblauwe** [comment]
Version 4.2.0 released with support for this.
