### ISSUE TITLE
Support snake_case Json Response Configuration for Error Responses

### ISSUE THREAD

**Issue by josephkajuch** [wimdeblauwe/error-handling-spring-boot-starter#75]
My API currently uses the snake_case variable/field naming convention via Spring Boot Object Mapper, is it possible to support snake case rather than exclusively camelCase for json response field names (and their internal references to fields/properties)?

For example: 
        {
            "code": "REQUIRED_NOT_NULL",
            "message": "must not be null",
            "property": "variableCamelCase",
            "rejectedValue": null,
            "path": "variableCamelCase"
        }

Would become instead:
        {
            "code": "REQUIRED_NOT_NULL",
            "message": "must not be null",
            "property": "variable_camel_case",
            "rejected_value": null,
            "path": "variable_camel_case"
        }

**Comment by wimdeblauwe** [comment]
It is not possible out of the box, but you can do the following:

1. Create your own `ApiErrorResponseSerializer` class extending https://github.com/wimdeblauwe/error-handling-spring-boot-starter/blob/master/src/main/java/io/github/wimdeblauwe/errorhandlingspringbootstarter/ApiErrorResponseSerializer.java
2. Expose a bean in your application with your custom `ApiErrorResponseSerializer`.

The bean in your own application will normally take precedence.

E.g.:

```
public class MyApiErrorResponseSerializer extends ApiErrorResponseSerializer {
  public MyApiErrorResponseSerializer(ErrorHandlingProperties properties) {
    super(properties);
  }

  @Override
  public void serialize(ApiErrorResponse errorResponse,
                          JsonGenerator jsonGenerator,
                          SerializerProvider serializerProvider) throws IOException {
      // add your custom logic here, probably copying over most of the original method body
   }
}
```

In your own configuration class:

```
    @Bean
    public MyApiErrorResponseSerializer apiErrorResponseSerializer(ErrorHandlingProperties properties) {
        return new MyApiErrorResponseSerializer(properties);
    }
```

**Comment by wimdeblauwe** [comment]
Do you have any more questions on this? Can I close the issue?
