### ISSUE TITLE
Global Error response customization 

### ISSUE THREAD

**Issue by wojciechGaudnik** [wimdeblauwe/error-handling-spring-boot-starter#76]
Hi,

Is there a way to add some global customizations, such as adding a timestamp or tracing, to all error responses?

Best regards

**Comment by wimdeblauwe** [comment]
See https://wimdeblauwe.github.io/error-handling-spring-boot-starter/current/#global-customization-of-the-response-json

**Comment by wojciechGaudnik** [comment]
Hi, 
my mistake, I forgot add number 3.4.1. I cannot update to java 17.

**Comment by wimdeblauwe** [comment]
If you need support for older versions, please contact me through [my company](https://www.widit.be/).
