### ISSUE TITLE
Extend the library to handle Graphql errors

### ISSUE THREAD

**Issue by robertionut95b** [wimdeblauwe/error-handling-spring-boot-starter#78]
Hello!

I think the library would grow even more if considered to include GraphQL error handling. There are a few implementations already for java-graphql and Spring framework (DGS, Kickstart, Spring GraphQL, etc.) but not many offer a simple, highly configurable error handling setup.

The main contract from which all error handlers would start is similar to the current implementation:

```java
import graphql.GraphQLError;

public interface GraphqlExceptionHandler {

    boolean canHandle(Throwable throwable);

    GraphQLError handleError(Throwable throwable);
}
```

The only specific feature would be to implement a specialized bean or extend an ExceptionHandler interface required for the library to work.

Example for DGS:

```java
@Component
public class CustomDataFetchingExceptionHandler implements DataFetcherExceptionHandler {

   @Override
   public CompletableFuture<DataFetcherExceptionHandlerResult> handleException(DataFetcherExceptionHandlerParameters handlerParameters) {
      if (handlerParameters.getException() instanceof MyException) {
         Map<String, Object> debugInfo = new HashMap<>();
         debugInfo.put("somefield", "somevalue");

         GraphQLError graphqlError = TypedGraphQLError.newInternalErrorBuilder()
                 .message("This custom thing went wrong!")
                 .debugInfo(debugInfo)
                 .path(handlerParameters.getPath()).build();

         DataFetcherExceptionHandlerResult result = DataFetcherExceptionHandlerResult.newResult()
                 .error(graphqlError)
                 .build();

         return CompletableFuture.completedFuture(result);
      } else {
         return DataFetcherExceptionHandler.super.handleException(handlerParameters);
      }
   }
}
```

What do you think about this?

**Comment by wimdeblauwe** [comment]
I have no experience with GraphQL at all, so this is not something I need. But if you are willing to develop and maintain the feature in such a way that people not using GraphQL are not getting extra dependencies they don't want, then I am willing to review the PR.

**Comment by robertionut95b** [comment]
A baseline implementation for Spring would require at least [spring-graphql](https://github.com/spring-projects/spring-graphql).

If this is no issue I might try to invest some time in a PR.

**Comment by wimdeblauwe** [comment]
I assume we can add it as an optional dependency

**Comment by robertionut95b** [comment]
Issued #80, thanks!
