### ISSUE TITLE
Global Error clarification

### ISSUE THREAD

**Issue by bwgjoseph** [wimdeblauwe/error-handling-spring-boot-starter#79]
Hi,

Based on the [docs](https://wimdeblauwe.github.io/error-handling-spring-boot-starter/4.2.0/#validation), it states any global error will be listed in the json like such as suggested in the docs

```json
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 4",
  "globalErrors": [
    {
      "code": "ValidCustomer",
      "message": "Invalid customer"
    },
    {
      "code": "ValidCustomer",
      "message": "UserAlreadyExists"
    }
  ]
}
```

And it is based on the following class

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Constraint(validatedBy = CustomerValidator.class)
public @interface ValidCustomer {
    String message() default "Invalid customer";

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};
}
```

So I get that the code is using the `ClassName`, and the message is based on the `default message`. However, in the `note` section of the doc, it gave another example

```json
{
  "code": "VALIDATION_FAILED",
  "message": "Validation failed for object='exampleRequestBody'. Error count: 2",
  "globalErrors": [
    {
      "code": "INVALID_CUSTOMER",
      "message": "Invalid customer"
    },
    {
      "code": "INVALID_CUSTOMER",
      "message": "The user already exists"
    }
  ]
}
```

How did the `code` changed from `ValidCustomer` to `INVALID_CUSTOMER`?

---

The reason to ask this is to see if there's a way to override the `code` since the message can be override easily.

Thanks!

**Comment by wimdeblauwe** [comment]
You can add a property in your `application.properties` like this:

```
error.handling.codes.ValidCustomer=INVALID_CUSTOMER
```

This is explained in the docs here: https://wimdeblauwe.github.io/error-handling-spring-boot-starter/current/#general-override-of-validation-error-codes

**Comment by bwgjoseph** [comment]
Thanks for pointing that out!
