### ISSUE TITLE
Include validation errors based on exception type

### ISSUE THREAD

**Issue by donalmurtagh** [wimdeblauwe/error-handling-spring-boot-starter#85]
In [section 3.5.1](https://wimdeblauwe.github.io/error-handling-spring-boot-starter/current/#validation), the circumstances under which validation errors are included in the response are documented, but I would like to be able to have them included based on the type of the exception.

I have a custom exception class that looks like this

```java
import org.springframework.validation.FieldError;

public class MyValidationException extends RuntimeException {

    private final List<FieldError> fieldErrors;

    public MyValidationException(List<FieldError> fieldErrors) {
        super("Validation failed");
        this.fieldErrors = fieldErrors;
    }

    public List<FieldError> getFieldErrors() {
        return this.fieldErrors;
    }
}
```

When an exception of this type is thrown, the field errors are ignored, because at the moment they are only included in
the response for exception types such as `MethodArgumentNotValidException` and `ConstraintViolationException`.

Is there a way that this list could be extended, e.g. by making the custom exception class implement a particular interface or by annotating the methods that expose the error data?

I've only considered the field errors in the example above, but presumably the solution should also support custom exception classes that expose global/parameter errors.

**Comment by wimdeblauwe** [comment]
Have you looked at [Adding extra properties in the response](https://wimdeblauwe.github.io/error-handling-spring-boot-starter/current/#adding-extra-properties-in-the-response) ?

**Comment by donalmurtagh** [comment]
It didn't occur to me to use that. So if I replace `getFieldErrors` above with

```java
@ResponseErrorProperty
public List<ApiFieldError> getFieldErrors()
```

Then I guess the response should look the same as it does for the Spring validation exceptions?

**Comment by wimdeblauwe** [comment]
I suggest to give it a try and see what happens :)
