### ISSUE TITLE
Document exactly which exception types produce `fieldErrors` in the response

### ISSUE THREAD

**Issue by donalmurtagh** [wimdeblauwe/error-handling-spring-boot-starter#86]
The documentation says

> For some exceptions like [MethodArgumentNotValidException](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/MethodArgumentNotValidException.html), [ConstraintViolationException](https://docs.oracle.com/javaee/7/api/javax/validation/ConstraintViolationException.html),…​ there is special handling and extra information is returned in the response.

But it would be helpful to know _exactly_ which exception types produce this extra information, e.g. is it

 - all exceptions that are instances of a base class of MethodArgumentNotValidException, ConstraintViolationException, etc
 - all exceptions that are instances of MethodArgumentNotValidException, ConstraintViolationException, etc
 - all exceptions that are instances of MethodArgumentNotValidException, ConstraintViolationException, etc or any subclass of these
 - something else...

**Comment by wimdeblauwe** [comment]
I believe that if you want to know it so exact, you should look at the source code. The documentation just gives some examples. It is not the intention to have an exhaustive list there.
