### ISSUE TITLE
Using of @ResponseErrorProperty out of the constructor

### ISSUE THREAD

**Issue by yonchev** [wimdeblauwe/error-handling-spring-boot-starter#96]
Hello, this is not an issue, but I couldn't find anywhere else to ask.

I want to show extra properties but without putting them in the constructor. I have a specific exception that I receive from an external API and I would like to parse it in the exception class, but my properties, even though I load them, end up showing null values. Is there a way to do this or do I have to do my parsing before I throw my exception?
I would be very grateful if you could help me.

Here is my exception class

```
@ResponseStatus(HttpStatus.BAD_REQUEST)
@ResponseErrorCode("DOCUMENT_SERVICE_ERROR")
@Slf4j
public class DocumentServiceException extends RuntimeException {
    @ResponseErrorProperty(includeIfNull=true)
    private JSONArray violations;

    @ResponseErrorProperty(includeIfNull=true)
    private String url;

    @ResponseErrorProperty(includeIfNull=true)
    private String title;

    public DocumentServiceException(String msg) {
        super(msg);
        log.error(msg);
    }

    public DocumentServiceException(HttpClientErrorException ex) {
        super("Error from DS API");
        String jsonString = ex.getMessage().substring(ex.getMessage().indexOf(":") + 2);
        //remove first and last \"
        if (jsonString.startsWith("\"") && jsonString.endsWith("\"")) {
            jsonString = jsonString.substring(1, jsonString.length() - 1);
        }
        JSONObject obj = new JSONObject(jsonString);
        this.violations = obj.getJSONArray("violations");
        this.url = obj.getString("instance");
        this.title = obj.getString("title");
        log.error("Error from DS API, {} {} {}", this.url, this.title, this.violations);
    }
}
```

**Comment by wimdeblauwe** [comment]
I don't see anything wrong at first sight. If you assign a value to your fields in the constructor like you seem to do, then things should work. Have you tried using a debugger to ensure the values are properly assigned to the fields?

**Comment by wimdeblauwe** [comment]
Closing this issue as no feedback is provided.
