### ISSUE TITLE
Spring Boot 3.3.2 throws AuthorizationDeniedException instead of AccesDeniedException

### ISSUE THREAD

**Issue by BartDuwez** [wimdeblauwe/error-handling-spring-boot-starter#97]
Hi Wim,

we are running into an issue where spring security is throwing an AuthorizationDeniedException instead of an AccessDeniedException. This exception is not handled in the io.github.wimdeblauwe.errorhandlingspringbootstarter.handler.SpringSecurityApiExceptionHandler as it does not yet exist in the spring boot version you are using. This causes the http response to be 500 instead of 403.

This is a new exception that comes with the spring boot update. Do you have any plans regarding updating your library?

Kind regards,
Bart

**Comment by wimdeblauwe** [comment]
Thank you for your report. I see that this class is new in Spring Boot 3.3.x which means that if I want to support this, I will need to make the library compatible with that version and above only.

For now, you can manually override the response code via `application.properties` like this:

```
error.handling.codes.org.springframework.security.authorization.AuthorizationDeniedException=forbidden
```

**Comment by BartDuwez** [comment]
Hi Wim, we tried this. It turns out we had to use "http-statuses" instead of "codes". No worries!

**Comment by wimdeblauwe** [comment]
Ah, right! 👍

**Comment by wimdeblauwe** [comment]
@bwgjoseph Please open a separate issue instead of hijacking another issue. That said, you do need to configure your web security configuration like in the mentioned documentation links for this to work.
